### ISSUE TITLE
Change to Using Voltage Compensating Techniques on Talons

### ISSUE THREAD

**Issue by rgreenblatt** [FRC900/tasks#107]
Instead of percent vbus we should be using Voltage Compensation Mode.
We should also set nominal closed loop voltage (applies voltage compensation for closed loop control modes).

See http://www.ctr-electronics.com/downloads/pdf/Talon%20SRX%20Software%20Reference%20Manual.pdf for details.

**Comment by kjaget** [comment]
Support added for controllers & YAML config in https://github.com/FRC900/2017Preseason/commit/f419e8d3702302f1533fd0e72e1b5ae423309d1a and https://github.com/FRC900/ros_control_boilerplate/commit/5848dca3861c4ddf38c8f1d61ccf9f769d86f27d

If we need to do this dynamically in code we need to add code to talon_controller_interface to expose the options to the controller code using the controller_interfaces.  But if this is set once at startup via config file we're done

**Comment by rgreenblatt** [comment]
The support is there to do this now, we need to remember to implement this functionality.
