### ISSUE TITLE
Add Current Limit Function to Talon Interface

### ISSUE THREAD

**Issue by rgreenblatt** [FRC900/tasks#108]
The talon's can apply a limit to current. We should be able to set it during runtime and/or in a static config file.

**Comment by kjaget** [comment]
https://github.com/FRC900/2017Preseason/commit/90cde1787ea3730fa7ff7391612b0e1674683790 and https://github.com/FRC900/ros_control_boilerplate/commit/1a034c4aa3b8e3abd28a7b71ab85a6ef13687664
