### ISSUE TITLE
Convert to/from native units in hardware_interface

### ISSUE THREAD

**Issue by kjaget** [FRC900/tasks#115]
Right now setpoint and encoder position&speed come from the Talon in various units depending on Talon mode, encoder type selected and in some cases the actual encoder attached.  One of the jobs of the hardware interface should be to convert those to standard units.  My proposal for those units is radians (for position) and radians/sec (for speed).  By picking these common units, higher level code can send request in that unit and the hardware interface will sort out the details depending on how the talon is configured.

To do this we need new methods in the frcrobot_hw_interface code.  One should take a reading from an encoder in native units from the talon and covert it to radians or radians/sec. Not sure if this is one method or two - let's see if speed and position have the same conversion factor (I'm guessing yes, but I'm not totally convinced).  The other functino will work in reverse - pass in a radian or radian/sec and return a value in native units.

For some cases, knowing the mode should be enough.  For example, %vbus mode shouldn't do any conversion.  Probably the same for current-close-loop mode. 

In other cases (speed and position close loop) you'll have to know the mode and encoder type.  That'll work with encoders which the Talon knows about (CTRE magnetic, for example).  For feedback modes with encoders we don't know about (e.g. generic quad  encoders), you'll have to add a config item to define a ticks per rotation.

Work items:

1. Add methods to talon_command_interface and talon_state_interface to set/store FeedbackDevice settings.
1a.  Add an enum with the following entries : 
   QuadEncoder
    AnalogPot
    AnalogEncoder    
EncRising
    EncFalling
    CtreMagEncoder_Relative
    CtreMagEncoder_Absolute
    PulseWidth
plus an uninitialized and last enum.  Look to TalonMode for inspiration.
1b. add an encoder_feedback member var (of type enum defined in 1a) to both talon_state_interface and talon_command_interface.  Add setters and getters as with any other member var
1c. add an encoder_tick_per_rotation member var.  This should be an int. It'll be like any other command/state var, so add setters and getters as appropriate in both state and command.
2. Add code to TalonCommandInterface to initialize this from a parameter. 
2a. Add a member var to TalonCIParams (in talon_controller_interface) of the enum type in 1a.  Make sure to initialize it to unknown in the constructor.
2b. Add code to read it from a param.  It'll be sorta like readJointName, except instead of reading directly into a string member var, read into a local string var. Then do a conversion from the input string to one of the enumerated types defined in 1a : `if (in_string == "QuadEncoder" _ =  feedback_type=FeedbakType_QuadEncoder; else if (blah blah blah) ...`
2c.. Update TalonControllerInterface to call the code added in 2b ... add it to readParams()
2d.  Use this value to call the talon_command method added in 1b.
2e. Using similar steps, add a parameter called ticks_per_rotation. It should be an integer-valued member.   Using steps similar to the ones above, add a member var to hold the param, code to read from param, and code to set it in talon_command  
3. frcrobot_hw_interface changes
3a. Add code in write to copy from talon_command_ feedback device into talon_state feedback device. Mimic the stuff for inverts
3b. do the same for the encoder ticks per rotation setting
3c. Create methods to convert between native Talon and ROS units.  These methods will probably end up being private members of the hw_interface, which means they'll have access to talon mode, feedback device, and user configured ticks per rotation.
3d.  Use this method to convert the read() code for position and speed as well as the write code for command.

**Comment by kjaget** [comment]
Assigned various people.  o-fugi should be in the middle of similar code for item 1.  FlashTheDash was in the code for item 2 so tag he's it.  And FW touched the code in 3 last so it's now his problem.

Feel free to volunteer other people to help with these tasks.  The more people who understand the code the quicker we can get stuff done in the future, so if you understand something find someone to teach as you do the work.  Leadership!

Let me know if you have questions.

**Comment by kjaget** [comment]
Ryan posted a nice cheat sheet for what Talon values get used in which cases  : https://files.slack.com/files-pri/T09M61H4Z-F88VAS1NZ/image.png

Note that motion profiling is a giant TBD as far as I'm concerned - if we get this working for %vbus and the close loop stuff that's a great start.

**Comment by rgreenblatt** [comment]
Documentation available on page 133-139 (particularly 137) of the [Talon Software Reference Manual](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwivgtDh3_rXAhWuSd8KHXbRAB8QFggwMAE&url=https%3A%2F%2Fwww.ctr-electronics.com%2FTalon%2520SRX%2520Software%2520Reference%2520Manual.pdf&usg=AOvVaw1f0NgV4IS_kCbJLRwxvdHy)

**Comment by kjaget** [comment]
The latest beta code has changed the list of feedback devices.  We'll have to update to match.

	None
	QuadEncoder
	Analog
	Tachometer
	PulseWidthEncodedPosition
	SensorSum
	SensorDifference
	Inertial
	RemoteSensor
	SoftwareEmulatedSensor 
	CTRE_MagEncoder_Absolute = PulseWidthEncodedPosition,
	CTRE_MagEncoder_Relative = QuadEncoder

The last two are used to alias CTRE products to the generic type they operate as.  Define them as listed above and they should work fine

**Comment by kjaget** [comment]
List of things to convert aside from Set() input and getposition/velocity :

setpoint?
Closed loop error (change to float - read from talon as integral native units but conversion to radians will be a float)
integral accumllator
error derivative 
Softlimits (same as above)

**Comment by o-fugi** [comment]
This is done and working. See [https://github.com/FRC900/2018RobotCode/blob/e1082b7cf25bca4cab7e410df583372cfd8cce1f/zebROS_ws/src/ros_control_boilerplate/src/frcrobot_hw_interface.cpp#L477](url)
