### ISSUE TITLE
Email Pixelmator

### ISSUE THREAD

**Issue by sofiasanchez** [FRC900/tasks#122]
Beg for free software (photoshop replacement)

**Comment by marshallmassengill** [comment]
Website:

http://www.pixelmator.com/pro/

Contact:

info@pixelmator.com

Tell them you tried reaching out to Adobe but they wouldn't give you the
time of day... they'll appreciate the humor and professional rivalry will
kick in.

---Marshall

**Comment by sucheta-m** [comment]
giving software in future
