### ISSUE TITLE
Publish game-specific message from hw_interface

### ISSUE THREAD

**Issue by kjaget** [FRC900/tasks#133]
Probably best to make it either a separate message or maybe include other game state - match time, alliance color and position, etc.

See http://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/826278-2018-game-data-details for how to access it.

Use a realtime_publisher from the hal_keepalive_thread. Should be kinda similar to the joystick publishing code in there

**Comment by o-fugi** [comment]
Added MatchSpecificData.msg and added publisher in hw_interface. See [https://github.com/FRC900/2018RobotCode/commit/ee02107fa165708c664c569ba2830761ff1a531a](url).
