### ISSUE TITLE
Add pneumatic support to hardware_interface

### ISSUE THREAD

**Issue by amstrudy** [FRC900/tasks#155]

**Comment by kjaget** [comment]
Going to have some similarities to https://github.com/FRC900/tasks/issues/128

C++ docs here : https://wpilib.screenstepslive.com/s/currentCS/m/cpp/l/241866-operating-pneumatic-cylinders-solenoids

Looks like we'll need two types - single and double?  And we'll have to map on/off/forward/reverse to float values unless we want to create a whole new interface type for them.

**Comment by rgreenblatt** [comment]
Theoretically done, needs testing.

**Comment by rgreenblatt** [comment]
tested and working
