### ISSUE TITLE
make a priority list of sensors

### ISSUE THREAD

**Issue by sucheta-m** [FRC900/tasks#164]

**Comment by rgreenblatt** [comment]
See mechanical design doc here: [https://docs.google.com/document/d/1HZAiwslh3vx1uS1NhE-StnltxsRqDmKs-XJDrIaDj0c/edit](https://docs.google.com/document/d/1HZAiwslh3vx1uS1NhE-StnltxsRqDmKs-XJDrIaDj0c/edit)

(Also posted in ROS)
