### ISSUE TITLE
Get navX C++ library working on the RIO. 

### ISSUE THREAD

**Issue by rgreenblatt** [FRC900/tasks#178]
See: [https://www.pdocs.kauailabs.com/navx-mxp/software/roborio-libraries/c/](https://www.pdocs.kauailabs.com/navx-mxp/software/roborio-libraries/c/)
For hooking this up with a hardware interface see #129

**Comment by eblau** [comment]
I added instructions to `setup_cross_build.sh` for how to install the navX-MXP library and include files and updated the [Docker image ](https://github.com/FRC900/ZebraWiki/wiki/Docker-development-environment-for-ROS). Installation is similar to the Talon libraries. They are installed underneath `~/wpilib/user/cpp`. Updated the ros_control_boilerplate CMakeLists.txt file to link with the navX library as well.

**Comment by kjaget** [comment]
done
