### ISSUE TITLE
ROS-control node on RoboRIO

### ISSUE THREAD

**Issue by sucheta-m** [FRC900/tasks#4]
@sucheta-m commented on [Mon Sep 25 2017](https://github.com/FRC900/tasks/issues/2)

Description: Transfer existing useful code, learn about open-source ROS code which might apply

**Comment by kjaget** [comment]
Model main control node on the RIO after this : https://github.com/FRC900/ros_control_boilerplate
Swerve drive example : https://github.com/FRC900/steered_wheel_base_controller
Will need other control libraries for different mechanisms.
