### ISSUE TITLE
Start adding dynamic reconfigure for talon control params

### ISSUE THREAD

**Issue by kjaget** [FRC900/tasks#68]
Ros has the option to allow users to change parameters during runtime.  This is described in their docs for dynamic reconfigure : http://wiki.ros.org/dynamic_reconfigure

We want this option for many of the Talon parameters.  Start with the p/i/d/f/i_zone vars we just added. To get an idea of how this will work go through the tutorials here :  http://wiki.ros.org/dynamic_reconfigure/Tutorials

For a more concise walkthru, follow the steps here : http://wiki.ros.org/dynamic_reconfigure/Tutorials/SettingUpDynamicReconfigureForANode

All of this should be in the zebROS_ws/src/talon_controllers subdir.
Note that for step 1, you'll be changing package.xml instead of manifest.xml (docs are out of date a bit)
For the .cfg file, add 2 sets of PID values. Since this feature can't handle arrays, they'll need to be something like p0, i0, d0, etc, p1, i1, d1 ... corresponding to p_[0], i_[0] ... p_[1], i_[1] in the code.  Or maybe set up two groups, one for slot 0 and one for slot 1. Each would have p/i/d/f/izone?

The callback function in the example will be a member of TalonControllerInterface, in zebROS_ws/src/talon_controllers/include/talon_controllers/talon_controller_interface.h.  It should copy the new parameter values (the argument to the callback function) into params_ then call writeParamsToHW().  The syntax of the callback might be tricky - get it close and we can work on it together

For the CMakeLists.txt additions, be sure to use the "or if your ROS distribution is Groovy or higher use this: " block of text

**Comment by eblau** [comment]
@FlashTheDash and I are working on this.
