### ISSUE TITLE
Common Units for Programming

### ISSUE THREAD

**Issue by rgreenblatt** [FRC900/tasks#89]
We need to make a list which contains all the units we will use.
For example:
Temp - K
Mass - Kg
Power - W
Energy - J
etc.

**Comment by kjaget** [comment]
http://www.ros.org/reps/rep-0103.html

Meters, radians, right-handed coord system with positive X being forward, etc.

**Comment by kjaget** [comment]
Let me reiterate .. we are not using Kelvin for units of temperature, and it is not up for vote :)

**Comment by Judissimo** [comment]
Can we use the Leiden scale?


------ Original Message ------

**Comment by kjaget** [comment]
Good enough for now.
