### ISSUE TITLE
Make page in Wiki for setting up workspace with ROS and OpenCV

### ISSUE THREAD

**Issue by amstrudy** [FRC900/tasks#97]

**Comment by amstrudy** [comment]
This task is complete. Here is the link to the wiki: https://github.com/FRC900/ZebraWiki/wiki/Setting-up-a-VirtualBox-workspace-with-ROS-and-OpenCV

**Comment by kjaget** [comment]
Not so fast - is this linked from one of the programming pages? I couldn't find it but that might just be me.

**Comment by amstrudy** [comment]
It's on the Programming page under vision I think!
